# Generated by Django 5.2.4 on 2025-08-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('documents', models.JSONField()),
                ('status', models.CharField(default='Pending')),
                ('delivery_range', models.FloatField(default=5)),
                ('gst_no', models.CharField(max_length=55)),
                ('other_no', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=355)),
                ('role', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=450)),
                ('is_verified', models.BooleanField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1255)),
                ('quantity', models.CharField(max_length=155)),
                ('discount', models.CharField(max_length=155)),
                ('images', models.JSONField()),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.seller')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.user'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=155)),
                ('price', models.CharField(max_length=99)),
                ('status', models.CharField(max_length=155)),
                ('discount', models.CharField(max_length=155)),
                ('payment_type', models.CharField(max_length=555)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('addtocart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=155)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=155)),
                ('pincode', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=255)),
                ('documents', models.JSONField()),
                ('status', models.CharField(default='Pending')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.seller')),
            ],
        ),
    ]
