# Generated by Django 5.2.4 on 2025-10-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuicklyCart_app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.AutoField(primary_key=True, serialize=False)),
                ('documents', models.JSONField()),
                ('status', models.CharField(default='Pending')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuicklyCart_app.user')),
            ],
        ),
    ]
