# Generated by Django 5.2.4 on 2025-10-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuicklyCart_app', '0003_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='verification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='verification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
