# Generated by Django 5.2.4 on 2025-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuicklyCart_app', '0004_rider_reject_reason_rider_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
