# Generated by Django 5.2.4 on 2025-11-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuicklyCart_app', '0005_rider_is_available_rider_last_location_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='longitude',
        ),
        migrations.AddField(
            model_name='rider',
            name='km_away',
            field=models.CharField(default=3),
        ),
        migrations.CreateModel(
            name='RiderOrder',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('pickup_address', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_address', models.CharField(blank=True, default='', max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_events', to='QuicklyCart_app.order')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_account', to='QuicklyCart_app.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account', to='QuicklyCart_app.user')),
            ],
        ),
    ]
